<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZNC4oNW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZNC4oNW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZNC4oNW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZNC4oNW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZNC4oNW\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZNC4oNW',
    'container.build_id' => 'ae89ca35',
    'container.build_time' => 1585491139,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZNC4oNW');
